---
  services:
  - service_name: universal-app
    image_name: universal-app
    container_name: universal-app
    port_host: 8888
    port_container: 4000
    network_name: universal-app_net
  dockerfile:
  - angular_project_name: universal-app